package service

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"hash"
	"strings"

	"github.com/QuantumNous/new-api/common"
)

const generatedMediaBufferLimit = 1 << 20

type generatedMediaFilter struct {
	buffer   []byte
	dropping bool
	sse      bool
	hash     hash.Hash
	size     int64
}

// generatedMediaOmission is deliberately self-describing so later training
// cleanup can distinguish policy redaction from corruption or missing data.
type generatedMediaOmission struct {
	Omitted      string `json:"omitted"`
	SHA256       string `json:"sha256"`
	EncodedBytes int64  `json:"encoded_bytes"`
	DecodedBytes int64  `json:"decoded_bytes,omitempty"`
}

func (f *generatedMediaFilter) Append(data []byte, final bool) ([]byte, int) {
	if len(data) > 0 {
		f.buffer = append(f.buffer, data...)
	}
	var output bytes.Buffer
	omissions := 0
	for {
		if f.dropping {
			if f.hash == nil {
				f.hash = sha256.New()
			}
			if !f.sse && !final {
				_, _ = f.hash.Write(f.buffer)
				f.size += int64(len(f.buffer))
				f.buffer = f.buffer[:0]
				break
			}
			boundary := len(f.buffer)
			if f.sse {
				index, boundarySize := sseBoundary(f.buffer)
				if index < 0 && !final {
					_, _ = f.hash.Write(f.buffer)
					f.size += int64(len(f.buffer))
					f.buffer = f.buffer[:0]
					break
				}
				if index >= 0 {
					boundary = index + boundarySize
				}
			}
			_, _ = f.hash.Write(f.buffer[:boundary])
			f.size += int64(boundary)
			marker, _ := common.Marshal(generatedMediaOmission{
				Omitted:      "generated_media_event",
				SHA256:       hex.EncodeToString(f.hash.Sum(nil)),
				EncodedBytes: f.size,
			})
			if f.sse {
				output.WriteString("data: ")
				output.Write(marker)
				output.WriteString("\n\n")
			} else {
				output.Write(marker)
			}
			omissions++
			f.buffer = append(f.buffer[:0], f.buffer[boundary:]...)
			f.dropping = false
			f.sse = false
			f.hash = nil
			f.size = 0
			if len(f.buffer) == 0 {
				break
			}
			continue
		}

		if sanitized, count, ok := sanitizeGeneratedMediaUnit(f.buffer); ok {
			output.Write(sanitized)
			omissions += count
			f.buffer = f.buffer[:0]
			break
		}
		if index := bytes.LastIndexByte(f.buffer, '\n'); index >= 0 {
			complete := f.buffer[:index+1]
			for len(complete) > 0 {
				lineEnd := bytes.IndexByte(complete, '\n')
				line := complete[:lineEnd+1]
				sanitized, count, _ := sanitizeGeneratedMediaUnit(line)
				output.Write(sanitized)
				omissions += count
				complete = complete[lineEnd+1:]
			}
			f.buffer = append(f.buffer[:0], f.buffer[index+1:]...)
			continue
		}
		if len(f.buffer) > generatedMediaBufferLimit && containsGeneratedMediaSignature(f.buffer) {
			f.dropping = true
			f.sse = bytes.HasPrefix(bytes.TrimSpace(f.buffer), []byte("data:"))
			continue
		}
		if len(f.buffer) > generatedMediaBufferLimit {
			// No generated-media field has appeared, so streaming this prefix is
			// safe and avoids turning unusually long text into a memory problem.
			// Keep a small overlap so a field name split across writes is still
			// detected before any generated bytes are emitted.
			const signatureOverlap = 128
			safeLength := len(f.buffer) - signatureOverlap
			output.Write(f.buffer[:safeLength])
			f.buffer = append(f.buffer[:0], f.buffer[safeLength:]...)
		}
		if final && len(f.buffer) > 0 {
			if containsGeneratedMediaSignature(f.buffer) {
				f.dropping = true
				f.sse = bytes.HasPrefix(bytes.TrimSpace(f.buffer), []byte("data:"))
				continue
			}
			output.Write(f.buffer)
			f.buffer = f.buffer[:0]
		}
		break
	}
	return output.Bytes(), omissions
}

func sseBoundary(data []byte) (int, int) {
	lf := bytes.Index(data, []byte("\n\n"))
	crlf := bytes.Index(data, []byte("\r\n\r\n"))
	switch {
	case lf < 0:
		return crlf, 4
	case crlf < 0 || lf < crlf:
		return lf, 2
	default:
		return crlf, 4
	}
}

func sanitizeGeneratedMediaUnit(data []byte) ([]byte, int, bool) {
	trimmed := bytes.TrimSpace(data)
	if len(trimmed) == 0 {
		return data, 0, true
	}
	prefix := []byte(nil)
	suffix := []byte(nil)
	jsonData := trimmed
	if bytes.HasPrefix(trimmed, []byte("data:")) {
		colon := bytes.IndexByte(data, ':')
		if colon < 0 {
			return data, 0, false
		}
		start := colon + 1
		for start < len(data) && (data[start] == ' ' || data[start] == '\t') {
			start++
		}
		end := len(data)
		for end > start && (data[end-1] == '\n' || data[end-1] == '\r') {
			end--
		}
		if bytes.Equal(bytes.TrimSpace(data[start:end]), []byte("[DONE]")) {
			return data, 0, true
		}
		prefix = data[:start]
		jsonData = data[start:end]
		suffix = data[end:]
	}
	var value any
	if err := common.Unmarshal(jsonData, &value); err != nil {
		return data, 0, false
	}
	count := redactGeneratedMedia(value)
	if count == 0 {
		return data, 0, true
	}
	encoded, err := common.Marshal(value)
	if err != nil {
		return data, 0, false
	}
	result := make([]byte, 0, len(prefix)+len(encoded)+len(suffix))
	result = append(result, prefix...)
	result = append(result, encoded...)
	result = append(result, suffix...)
	return result, count, true
}

func redactGeneratedMedia(value any) int {
	count := 0
	switch current := value.(type) {
	case map[string]any:
		eventType, _ := current["type"].(string)
		for key, child := range current {
			if encoded, ok := child.(string); ok && generatedMediaField(current, eventType, key) {
				current[key] = generatedMediaMarker(encoded)
				count++
				continue
			}
			count += redactGeneratedMedia(child)
		}
	case []any:
		for _, child := range current {
			count += redactGeneratedMedia(child)
		}
	}
	return count
}

func generatedMediaField(container map[string]any, eventType, key string) bool {
	normalizedType := strings.ToLower(eventType)
	normalizedKey := strings.ToLower(key)
	switch normalizedKey {
	case "partial_image_b64", "b64_json", "image_base64", "video_base64", "audio_base64":
		return true
	case "result":
		return strings.Contains(normalizedType, "image_generation") || normalizedType == "image_generation_call"
	case "data":
		mediaType := ""
		for _, mediaTypeKey := range []string{"mime_type", "mimeType", "media_type"} {
			if value, ok := container[mediaTypeKey].(string); ok {
				mediaType = strings.ToLower(value)
				break
			}
		}
		return strings.HasPrefix(mediaType, "image/") || strings.HasPrefix(mediaType, "audio/") || strings.HasPrefix(mediaType, "video/")
	default:
		return false
	}
}

func generatedMediaMarker(encoded string) generatedMediaOmission {
	raw, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		raw = []byte(encoded)
	}
	digest := sha256.Sum256(raw)
	return generatedMediaOmission{
		Omitted:      "generated_media",
		SHA256:       hex.EncodeToString(digest[:]),
		EncodedBytes: int64(len(encoded)),
		DecodedBytes: int64(len(raw)),
	}
}

func containsGeneratedMediaSignature(data []byte) bool {
	lower := strings.ToLower(string(data))
	for _, signature := range []string{`"partial_image_b64"`, `"b64_json"`, `"image_base64"`, `"video_base64"`, `"audio_base64"`, `"image_generation_call"`, `"inlinedata"`} {
		if strings.Contains(lower, signature) {
			return true
		}
	}
	if strings.Contains(lower, `"data"`) && (strings.Contains(lower, "image/") || strings.Contains(lower, "audio/") || strings.Contains(lower, "video/")) {
		return true
	}
	return false
}

func generatedMediaMetadata(count int) string {
	return fmt.Sprintf("%d", count)
}

func hasUnpinnedConversationAttachment(request []byte) bool {
	var value any
	if err := common.Unmarshal(request, &value); err != nil {
		return false
	}
	return containsRemoteAttachment(value, "", "")
}

func containsRemoteAttachment(value any, parentKey, parentType string) bool {
	switch current := value.(type) {
	case map[string]any:
		currentType, _ := current["type"].(string)
		for key, child := range current {
			if text, ok := child.(string); ok && isRemoteURL(text) {
				normalizedKey := strings.ToLower(key)
				normalizedParent := strings.ToLower(parentKey)
				normalizedType := strings.ToLower(currentType)
				if normalizedKey == "image_url" || normalizedKey == "file_url" || normalizedKey == "audio_url" ||
					normalizedParent == "image_url" || normalizedParent == "file_url" ||
					(normalizedKey == "url" && (strings.Contains(normalizedType, "image") || strings.Contains(strings.ToLower(parentType), "image"))) {
					return true
				}
			}
			if containsRemoteAttachment(child, key, currentType) {
				return true
			}
		}
	case []any:
		for _, child := range current {
			if containsRemoteAttachment(child, parentKey, parentType) {
				return true
			}
		}
	}
	return false
}

func isRemoteURL(value string) bool {
	lower := strings.ToLower(strings.TrimSpace(value))
	return strings.HasPrefix(lower, "https://") || strings.HasPrefix(lower, "http://")
}
